"""Migration + TimescaleDB integration tests against a real Postgres.

Gated on TEST_DATABASE_URL. Run with:

    docker compose -f docker-compose.test.yml up -d test-db
    export TEST_DATABASE_URL=postgresql+asyncpg://test:test@localhost:5433/qradar_obs_test
    (cd backend && pytest -m integration tests/integration/test_migrations.py)

Alembic uses the sync (psycopg) driver, so these tests derive a sync URL from
TEST_DATABASE_URL and drive Alembic's command API directly.
"""

from __future__ import annotations

import os

import pytest
from sqlalchemy import create_engine, text

pytestmark = pytest.mark.integration

TEST_DB_URL = os.environ.get("TEST_DATABASE_URL")


def _sync_url() -> str:
    if not TEST_DB_URL:
        pytest.skip("TEST_DATABASE_URL not set")
    return TEST_DB_URL.replace("+asyncpg", "+psycopg")


def _alembic_config(sync_url: str):
    from alembic.config import Config

    cfg = Config()
    cfg.set_main_option("script_location", "alembic")
    cfg.set_main_option("sqlalchemy.url", sync_url)
    return cfg


@pytest.fixture
def clean_db() -> str:
    """Drop everything (including timescale-managed objects) before each test."""
    sync_url = _sync_url()
    engine = create_engine(sync_url, future=True)
    with engine.begin() as conn:
        conn.execute(text("DROP SCHEMA public CASCADE"))
        conn.execute(text("CREATE SCHEMA public"))
    engine.dispose()
    return sync_url


def _table_exists(engine, name: str) -> bool:
    with engine.connect() as conn:
        return bool(
            conn.execute(
                text("SELECT to_regclass(:n)").bindparams(n=f"public.{name}")
            ).scalar()
        )


def test_upgrade_from_empty(clean_db: str) -> None:
    from alembic import command

    command.upgrade(_alembic_config(clean_db), "head")

    engine = create_engine(clean_db, future=True)
    try:
        # A representative sample of the 23 tables must exist.
        for tbl in ("log_source", "scheduled_search", "alert", "log_source_metric",
                    "collection_watermark", "log_source_detector_state"):
            assert _table_exists(engine, tbl), f"{tbl} missing after upgrade"
    finally:
        engine.dispose()


def test_downgrade_then_reupgrade(clean_db: str) -> None:
    from alembic import command

    cfg = _alembic_config(clean_db)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    engine = create_engine(clean_db, future=True)
    try:
        assert not _table_exists(engine, "log_source"), "downgrade left tables behind"
    finally:
        engine.dispose()

    # Re-upgrade must succeed on the now-empty database.
    command.upgrade(cfg, "head")
    engine = create_engine(clean_db, future=True)
    try:
        assert _table_exists(engine, "log_source")
    finally:
        engine.dispose()


def test_timescale_extension_and_hypertables(clean_db: str) -> None:
    from alembic import command

    command.upgrade(_alembic_config(clean_db), "head")

    engine = create_engine(clean_db, future=True)
    try:
        with engine.connect() as conn:
            ext = conn.execute(
                text("SELECT 1 FROM pg_extension WHERE extname = 'timescaledb'")
            ).scalar()
            if ext is None:
                pytest.skip("timescaledb extension not installed in this image")

            hypertables = {
                row[0]
                for row in conn.execute(
                    text("SELECT hypertable_name FROM timescaledb_information.hypertables")
                )
            }
        assert {"log_source_metric", "search_result_metric", "rule_metric",
                "offense_snapshot"} <= hypertables
    finally:
        engine.dispose()


def test_retention_policy_is_not_applied_by_migration(clean_db: str) -> None:
    """Migrations must be non-destructive: no retention job after a bare upgrade."""
    from alembic import command

    command.upgrade(_alembic_config(clean_db), "head")

    engine = create_engine(clean_db, future=True)
    try:
        with engine.connect() as conn:
            if conn.execute(
                text("SELECT 1 FROM pg_extension WHERE extname = 'timescaledb'")
            ).scalar() is None:
                pytest.skip("timescaledb not installed")
            retention_jobs = conn.execute(
                text(
                    "SELECT count(*) FROM timescaledb_information.jobs "
                    "WHERE proc_name = 'policy_retention'"
                )
            ).scalar()
        assert retention_jobs == 0, "migration must not create destructive retention policies"
    finally:
        engine.dispose()


def test_alembic_check_reports_no_drift(clean_db: str) -> None:
    """`alembic check` must pass: the metadata matches the migrated schema."""
    from alembic.util.exc import AutogenerateDiffsDetected

    from alembic import command

    cfg = _alembic_config(clean_db)
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"schema drift detected between models and migrations:\n{exc}")
