"""initial schema + timescaledb hypertables

Revision ID: 0001
Revises:
Create Date: 2026-07-19

FROZEN PHASE 2 BASELINE.

This revision is an explicit, deterministic snapshot of the schema as it stood
at commit 630825e ("feat: complete phase 2 operator UI and result trends"). It
deliberately imports nothing from `app.models`.

`sec_token` and the notification webhook columns are declared here as plain
`sa.String`. In the ORM they use `EncryptedString`, a TypeDecorator whose `impl`
is `String`: the Fernet encryption is applied in the application layer and has
no DDL representation, so the emitted schema is identical either way.

It previously called `Base.metadata.create_all()`, which made the migration read
*live* model metadata: adding a model retroactively changed what this historical
revision created, so an empty database and an upgraded Phase 2 database
converged on different schemas. The DDL below was generated by autogenerating
against the Phase 2 model metadata at 630825e and then frozen here verbatim, so
what 0001 creates can never drift again. Phase 3 additions live in 0002.

NON-DESTRUCTIVE: creates hypertables but sets no retention or compression
policy. Retention drops data, so it must never be a hardcoded migration side
effect -- see app/services/timescale.py.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The Phase 2 time-series tables, with their partitioning column. Frozen: the
# Phase 3 hypertables are created by 0002, not here.
_HYPERTABLES: dict[str, str] = {
    "log_source_metric": "bucket_start",
    "search_result_metric": "bucket_start",
    "rule_metric": "bucket_start",
    "offense_snapshot": "captured_at",
}


def _timescale_available(bind: sa.engine.Connection) -> bool:
    return bool(
        bind.execute(
            sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
        ).scalar()
    )


def upgrade() -> None:
    op.create_table('alert',
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_anomaly_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert'))
    )
    op.create_index('ix_alert_opened', 'alert', ['opened_at'], unique=False)
    op.create_index('ix_alert_status_severity', 'alert', ['status', 'severity'], unique=False)
    op.create_index('uq_alert_active_dedup', 'alert', ['dedup_key'], unique=True, postgresql_where=sa.text("status <> 'RESOLVED'"))
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('oidc_subject', name=op.f('uq_app_user_oidc_subject'))
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_log_actor_time', 'audit_log', ['actor', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('qradar_instance',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('console_host', sa.String(length=255), nullable=False),
    sa.Column('api_version', sa.String(length=16), nullable=False),
    sa.Column('sec_token', sa.String(length=512), nullable=True),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('ca_bundle_path', sa.String(length=512), nullable=True),
    sa.Column('provider_kind', sa.String(length=16), nullable=False),
    sa.Column('mcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('mcp_base_url', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('qradar_version', sa.String(length=64), nullable=True),
    sa.Column('last_health_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qradar_instance')),
    sa.UniqueConstraint('name', name=op.f('uq_qradar_instance_name'))
    )
    op.create_table('role',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('scheduled_search',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('mitre_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aql_query', sa.Text(), nullable=False),
    sa.Column('query_version', sa.Integer(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=128), nullable=False),
    sa.Column('schedule_timezone', sa.String(length=64), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('threshold_operator', sa.String(length=4), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_time_range_hours', sa.Integer(), nullable=False),
    sa.Column('max_result_rows', sa.Integer(), nullable=False),
    sa.Column('visualization_type', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_result_rows > 0', name=op.f('ck_scheduled_search_result_rows_positive')),
    sa.CheckConstraint('max_time_range_hours > 0', name=op.f('ck_scheduled_search_time_range_positive')),
    sa.CheckConstraint('timeout_seconds > 0', name=op.f('ck_scheduled_search_timeout_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_search')),
    sa.UniqueConstraint('name', name=op.f('uq_scheduled_search_name'))
    )
    op.create_index(op.f('ix_scheduled_search_category'), 'scheduled_search', ['category'], unique=False)
    op.create_index('ix_scheduled_search_enabled', 'scheduled_search', ['enabled', 'next_run_at'], unique=False)
    op.create_table('alert_notification',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('transition', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name=op.f('fk_alert_notification_alert_id_alert'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_notification')),
    sa.UniqueConstraint('alert_id', 'transition', 'channel', 'target', name='uq_alert_notification_transition')
    )
    op.create_index('ix_alert_notification_alert', 'alert_notification', ['alert_id', 'channel'], unique=False)
    op.create_index('ix_alert_notification_dispatch', 'alert_notification', ['status', 'next_attempt_at'], unique=False)
    op.create_table('analytics_rule',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('qradar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=64), nullable=True),
    sa.Column('is_building_block', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('mitre_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('average_capacity', sa.Float(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qradar_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['qradar_instance.id'], name=op.f('fk_analytics_rule_instance_id_qradar_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_rule')),
    sa.UniqueConstraint('instance_id', 'qradar_id', name='uq_analytics_rule_instance_qradar_id')
    )
    op.create_index('ix_analytics_rule_enabled', 'analytics_rule', ['enabled'], unique=False)
    op.create_index(op.f('ix_analytics_rule_name'), 'analytics_rule', ['name'], unique=False)
    op.create_table('collection_watermark',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('collector', sa.String(length=64), nullable=False),
    sa.Column('watermark_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lag_seconds', sa.BigInteger(), nullable=True),
    sa.Column('intervals_collected', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['qradar_instance.id'], name=op.f('fk_collection_watermark_instance_id_qradar_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_watermark')),
    sa.UniqueConstraint('instance_id', 'collector', name='uq_collection_watermark_key')
    )
    op.create_index('ix_collection_watermark_instance', 'collection_watermark', ['instance_id'], unique=False)
    op.create_table('configuration_snapshot',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['qradar_instance.id'], name=op.f('fk_configuration_snapshot_instance_id_qradar_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_snapshot'))
    )
    op.create_index('ix_configuration_snapshot_object', 'configuration_snapshot', ['instance_id', 'object_type', 'object_id', 'captured_at'], unique=False)
    op.create_table('detection_coverage',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.String(length=32), nullable=False),
    sa.Column('technique_name', sa.String(length=255), nullable=True),
    sa.Column('tactic', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mapped_rule_count', sa.Integer(), nullable=False),
    sa.Column('enabled_rule_count', sa.Integer(), nullable=False),
    sa.Column('firing_rule_count', sa.Integer(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['qradar_instance.id'], name=op.f('fk_detection_coverage_instance_id_qradar_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_coverage')),
    sa.UniqueConstraint('instance_id', 'technique_id', name='uq_detection_coverage_technique')
    )
    op.create_index(op.f('ix_detection_coverage_technique_id'), 'detection_coverage', ['technique_id'], unique=False)
    op.create_table('log_source',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('qradar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.Column('protocol_type_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('qradar_status', sa.String(length=64), nullable=True),
    sa.Column('credibility', sa.Integer(), nullable=True),
    sa.Column('target_event_collector_id', sa.Integer(), nullable=True),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maintenance_reason', sa.Text(), nullable=True),
    sa.Column('expected_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('business_hours_only', sa.Boolean(), nullable=False),
    sa.Column('business_hours_start', sa.Integer(), nullable=False),
    sa.Column('business_hours_end', sa.Integer(), nullable=False),
    sa.Column('business_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('custom_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('health_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['qradar_instance.id'], name=op.f('fk_log_source_instance_id_qradar_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_source')),
    sa.UniqueConstraint('instance_id', 'qradar_id', name='uq_log_source_instance_qradar_id')
    )
    op.create_index('ix_log_source_monitoring', 'log_source', ['monitoring_enabled', 'criticality'], unique=False)
    op.create_index(op.f('ix_log_source_name'), 'log_source', ['name'], unique=False)
    op.create_table('offense_snapshot',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('qradar_offense_id', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('magnitude', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('credibility', sa.Integer(), nullable=True),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=False),
    sa.Column('offense_type', sa.Integer(), nullable=True),
    sa.Column('offense_source', sa.String(length=255), nullable=True),
    sa.Column('event_count', sa.BigInteger(), nullable=True),
    sa.Column('flow_count', sa.BigInteger(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age_seconds', sa.BigInteger(), nullable=True),
    sa.Column('closing_reason_id', sa.Integer(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('local_destination_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['qradar_instance.id'], name=op.f('fk_offense_snapshot_instance_id_qradar_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instance_id', 'qradar_offense_id', 'captured_at', name=op.f('pk_offense_snapshot'))
    )
    op.create_index('ix_offense_snapshot_captured', 'offense_snapshot', ['captured_at'], unique=False)
    op.create_index('ix_offense_snapshot_offense', 'offense_snapshot', ['instance_id', 'qradar_offense_id', 'captured_at'], unique=False)
    op.create_index('ix_offense_snapshot_open', 'offense_snapshot', ['status', 'captured_at'], unique=False)
    op.create_table('search_execution',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('query_version', sa.Integer(), nullable=False),
    sa.Column('run_key', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ariel_search_id', sa.String(length=128), nullable=True),
    sa.Column('ariel_status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.BigInteger(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('threshold_breached', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['scheduled_search.id'], name=op.f('fk_search_execution_search_id_scheduled_search'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_execution')),
    sa.UniqueConstraint('search_id', 'run_key', name='uq_search_execution_run_key')
    )
    op.create_index('ix_search_execution_search_started', 'search_execution', ['search_id', 'started_at'], unique=False)
    op.create_index('ix_search_execution_status', 'search_execution', ['status'], unique=False)
    op.create_table('search_query_version',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('aql_query', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['scheduled_search.id'], name=op.f('fk_search_query_version_search_id_scheduled_search'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_query_version')),
    sa.UniqueConstraint('search_id', 'version', name='uq_search_query_version_search_version')
    )
    op.create_table('user_role_link',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_link_role_id_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_role_link_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role_link'))
    )
    op.create_table('configuration_change',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=True),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['configuration_snapshot.id'], name=op.f('fk_configuration_change_snapshot_id_configuration_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_change'))
    )
    op.create_index('ix_configuration_change_detected', 'configuration_change', ['detected_at'], unique=False)
    op.create_index('ix_configuration_change_object', 'configuration_change', ['object_type', 'object_id'], unique=False)
    op.create_table('log_source_anomaly',
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('deviation_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_source_id'], ['log_source.id'], name=op.f('fk_log_source_anomaly_log_source_id_log_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_source_anomaly'))
    )
    op.create_index('ix_log_source_anomaly_detected', 'log_source_anomaly', ['detected_at'], unique=False)
    op.create_index('ix_log_source_anomaly_open', 'log_source_anomaly', ['log_source_id', 'anomaly_type', 'resolved_at'], unique=False)
    op.create_table('log_source_baseline',
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('mad', sa.Float(), nullable=False),
    sa.Column('p05', sa.Float(), nullable=True),
    sa.Column('p95', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('is_reliable', sa.Boolean(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_version', sa.Integer(), nullable=False),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hour BETWEEN 0 AND 23', name=op.f('ck_log_source_baseline_hour_range')),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name=op.f('ck_log_source_baseline_weekday_range')),
    sa.ForeignKeyConstraint(['log_source_id'], ['log_source.id'], name=op.f('fk_log_source_baseline_log_source_id_log_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_source_baseline')),
    sa.UniqueConstraint('log_source_id', 'metric_name', 'weekday', 'hour', name='uq_log_source_baseline_cell')
    )
    op.create_table('log_source_detector_state',
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=32), nullable=False),
    sa.Column('consecutive_anomalous', sa.Integer(), nullable=False),
    sa.Column('consecutive_healthy', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('last_interval_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_anomaly_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_source_id'], ['log_source.id'], name=op.f('fk_log_source_detector_state_log_source_id_log_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_source_detector_state')),
    sa.UniqueConstraint('log_source_id', 'anomaly_type', name='uq_detector_state_source_type')
    )
    op.create_table('log_source_metric',
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bucket_seconds', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.BigInteger(), nullable=False),
    sa.Column('average_eps', sa.Float(), nullable=False),
    sa.Column('peak_eps', sa.Float(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_delay_seconds', sa.Float(), nullable=True),
    sa.Column('unknown_event_count', sa.BigInteger(), nullable=False),
    sa.Column('stored_event_count', sa.BigInteger(), nullable=False),
    sa.Column('parsed_username_ratio', sa.Float(), nullable=True),
    sa.Column('parsed_source_ip_ratio', sa.Float(), nullable=True),
    sa.Column('distinct_qid_count', sa.Integer(), nullable=False),
    sa.Column('distinct_username_count', sa.Integer(), nullable=False),
    sa.Column('distinct_source_ip_count', sa.Integer(), nullable=False),
    sa.Column('collection_error_count', sa.Integer(), nullable=False),
    sa.Column('payload_signature', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['log_source.id'], name=op.f('fk_log_source_metric_log_source_id_log_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_source_id', 'bucket_start', name=op.f('pk_log_source_metric'))
    )
    op.create_index('ix_log_source_metric_source_time', 'log_source_metric', ['log_source_id', 'bucket_start'], unique=False)
    op.create_table('rule_metric',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bucket_seconds', sa.Integer(), nullable=False),
    sa.Column('fire_count', sa.BigInteger(), nullable=False),
    sa.Column('offense_contribution_count', sa.BigInteger(), nullable=False),
    sa.Column('false_positive_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['analytics_rule.id'], name=op.f('fk_rule_metric_rule_id_analytics_rule'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'bucket_start', name=op.f('pk_rule_metric'))
    )
    op.create_index('ix_rule_metric_rule_time', 'rule_metric', ['rule_id', 'bucket_start'], unique=False)
    op.create_table('search_result_metric',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_key', sa.String(length=255), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['search_execution.id'], name=op.f('fk_search_result_metric_execution_id_search_execution'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['scheduled_search.id'], name=op.f('fk_search_result_metric_search_id_scheduled_search'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id', 'bucket_start', 'metric_key', name=op.f('pk_search_result_metric'))
    )
    op.create_index('ix_search_result_metric_search_time', 'search_result_metric', ['search_id', 'bucket_start'], unique=False)

    # Hypertables. Skipped gracefully on a vanilla Postgres (e.g. a CI box
    # without the Timescale extension) so the migration still applies there.
    bind = op.get_bind()
    if not _timescale_available(bind):
        return

    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    for table, time_col in _HYPERTABLES.items():
        op.execute(
            sa.text(
                "SELECT create_hypertable(:t, :c, "
                "if_not_exists => TRUE, migrate_data => TRUE)"
            ).bindparams(t=table, c=time_col)
        )


def downgrade() -> None:
    # Dropping the tables removes their hypertable structure and any policy that
    # was later attached to them.
    op.drop_index('ix_search_result_metric_search_time', table_name='search_result_metric')
    op.drop_table('search_result_metric')
    op.drop_index('ix_rule_metric_rule_time', table_name='rule_metric')
    op.drop_table('rule_metric')
    op.drop_index('ix_log_source_metric_source_time', table_name='log_source_metric')
    op.drop_table('log_source_metric')
    op.drop_table('log_source_detector_state')
    op.drop_table('log_source_baseline')
    op.drop_index('ix_log_source_anomaly_open', table_name='log_source_anomaly')
    op.drop_index('ix_log_source_anomaly_detected', table_name='log_source_anomaly')
    op.drop_table('log_source_anomaly')
    op.drop_index('ix_configuration_change_object', table_name='configuration_change')
    op.drop_index('ix_configuration_change_detected', table_name='configuration_change')
    op.drop_table('configuration_change')
    op.drop_table('user_role_link')
    op.drop_table('search_query_version')
    op.drop_index('ix_search_execution_status', table_name='search_execution')
    op.drop_index('ix_search_execution_search_started', table_name='search_execution')
    op.drop_table('search_execution')
    op.drop_index('ix_offense_snapshot_open', table_name='offense_snapshot')
    op.drop_index('ix_offense_snapshot_offense', table_name='offense_snapshot')
    op.drop_index('ix_offense_snapshot_captured', table_name='offense_snapshot')
    op.drop_table('offense_snapshot')
    op.drop_index(op.f('ix_log_source_name'), table_name='log_source')
    op.drop_index('ix_log_source_monitoring', table_name='log_source')
    op.drop_table('log_source')
    op.drop_index(op.f('ix_detection_coverage_technique_id'), table_name='detection_coverage')
    op.drop_table('detection_coverage')
    op.drop_index('ix_configuration_snapshot_object', table_name='configuration_snapshot')
    op.drop_table('configuration_snapshot')
    op.drop_index('ix_collection_watermark_instance', table_name='collection_watermark')
    op.drop_table('collection_watermark')
    op.drop_index(op.f('ix_analytics_rule_name'), table_name='analytics_rule')
    op.drop_index('ix_analytics_rule_enabled', table_name='analytics_rule')
    op.drop_table('analytics_rule')
    op.drop_index('ix_alert_notification_dispatch', table_name='alert_notification')
    op.drop_index('ix_alert_notification_alert', table_name='alert_notification')
    op.drop_table('alert_notification')
    op.drop_index('ix_scheduled_search_enabled', table_name='scheduled_search')
    op.drop_index(op.f('ix_scheduled_search_category'), table_name='scheduled_search')
    op.drop_table('scheduled_search')
    op.drop_table('role')
    op.drop_table('qradar_instance')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index('ix_audit_log_actor_time', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index('uq_alert_active_dedup', table_name='alert', postgresql_where=sa.text("status <> 'RESOLVED'"))
    op.drop_index('ix_alert_status_severity', table_name='alert')
    op.drop_index('ix_alert_opened', table_name='alert')
    op.drop_table('alert')
